### ISSUE TITLE
Clean up the outputfile naming conventions and document

### ISSUE THREAD

**Issue by mikeaintworkin** [thisaintwork/iqss_gh_reporting#38]
There are a lot of variables for running the code at this point.
- [x] create a first draft of an explanation of the variables that are set using create_iq_snapshot_init in readme.md
- [x] create an updated convention for naming the output that takes into account that sometimes files will be read and other times the API will be the source of the input data.-tst
- [x] update the code to reflect the changes.
- [x] Test it

**Comment by mikeaintworkin** [comment]
I've spent today working on this.
It's touched all the main files.
I had to think again about decisions I made about file naming and challenge them. The filenames are generally built left to right from least volatile to most volatile.

I think what I've implemented and documented in the README.md makes sense in that having the workflow doesn't matter so much for the api runs but it may be more significant for the file runs.

I'm doing testing on the api and file runs in my local environment now before checking it all in.

**Comment by mikeaintworkin** [comment]
hit the api rate limit. time to leave it for now.

**Comment by mikeaintworkin** [comment]
starting to do check-ins now around #38 this is the comment that goes with pydata.
The naming conventions updating lead to some serious tangential work including re-organizing the initialization function, changing some of the behavior for input variables, and changing how I validate the input variables.  This still feels very amateur.  I know there are libraries for cleaning and validating input as well as best practices for passing many input variables and I'm looking forward to v2 to get to understand those better.

**Comment by mikeaintworkin** [comment]
I'm going to close this for now as being adequate for a first pass at a cleanup.
The results are here:
- [README.md](https://github.com/thisaintwork/iqss_gh_reporting/blob/master/README.md)
- reflected in code in pydata.py that controls the naming of the output directory and the output file name base.
- Reflected in the new format of the yaml file.

```
collection_flag:
        h: 'str: valid values: start | snapshot | end. api=required. file=Ignored.'
        v: ''
organization_name:
        h: 'str: e.g: IQSS. Always required.'
        v: IQSS
output_base_dir:
        h: 'str: /mnt/hgfs/iq_reporting_collab/run/out;no[ ,.-special_char] ok:''_''.
                No trailing /. api=ignored. file=Optional'
        v: ''
output_file_base_name:
        h: 'str: e.g. sprint_2023_05_03-snapshot-2023_05_22_11_00-api-000-orig  .api=ignored.
                file=not required.'
        v: ''
project_name:
        h: 'str: e.g: IQSS/dataverse. Always required.'
        v: IQSS/dataverse
sprint_name:
        h: 'str: e.g. sprint_2023_04_26;no[ ,.-special_char] ok:''_''; api=required.file=Ignored.'
        v: ''
src_dir_name:
        h: 'str: e.g: ~/iqss_gh_reporting/run/in no[ ,.-special_char] ok:''_'' no
                trailing /. api=ignored. file=required.'
        v: /mnt/hgfs/iq_reporting_collab/sprint_2023_05_10/start/
src_file_name:
        h: 'str: e.g: sprint_2023_05_03-snapshot-2023_05_22_11_00-api-000-orig.tsv
                .api=ignored. file=required.'
        v: 2023_05_10-21_55_01-May102023-start-r01-api-20230510215501-sized.tsv
src_type:
        h: 'str: valid values: api | file. Always required.'
        v: file
workflow_name:
        h: very short description or code.no[ ,.-special_char] ok:'_' Optional.
        v: 1strun
```
